function calculate(x, y) {
    return 1 + (x + y) / 2
}

let a = 1
let b = 2
let c = 3

console.log(calculate(a, b))
console.log(calculate(a, c))
console.log(calculate(b, c))


const sum = (p , q) =>{
    return p + q
} 
console.log(sum(b, c))

var assalam = "Assalamualikum"

let salam = (name) => {
    return (assalam + " " + name)
}

let name = prompt("Enter your name");

console.log(salam(name))

let func1 = ()=>{
    console.log("I am generated by function named func1")
}

func1()